### ISSUE TITLE
Assertion Error When Integrating with Express.js

### ISSUE THREAD

**Issue by handigarde** [AppPress/node-connect-datadog#4]
Integrating with Express.js causes the below assertion error:

```
AssertionError: false == true
at SharedHandle.add (cluster.js:97:3)
at queryServer (cluster.js:480:12)
at Worker.onmessage (cluster.js:438:7)
at ChildProcess.<anonymous> (cluster.js:692:8)
at ChildProcess.emit (events.js:129:20)
at handleMessage (child_process.js:324:10)
at Pipe.channel.onread (child_process.js:352:11)
```

The configuration currently being used within the express.js file is:

```
var datadogExpress;
if(config.advancedMonitoring === true && !/^win/.test(process.platform)) {
  var ddOptions = {
    'response_code': true,
    'method': true,
    'tags': ['touchten-platform:' + config.env]
  };
  datadogExpress = require('connect-datadog')(ddOptions);
}
```

**Comment by handigarde** [comment]
May be related to https://github.com/joyent/node/issues/9261

**Comment by Brightergy-SamarAcharya** [comment]
Can confirm this issue too. Its most probably related to 9261. Am waiting for fix but is there any temporary workaround? I've not yet been able to dig deeper.

**Comment by techgaun** [comment]
Can confirm this issue too in express 4. Its most probably related to 9261. Am waiting for fix but is there any temporary workaround? I've not yet been able to dig deeper.

**Comment by nodesocket** [comment]
:+1: Anybody have a fix?

We are running:

```
app.use(require('connect-datadog')({
            tags: ['Brandcast'],
            path: true,
            method: true,
            protocol: true,
            response_code: true
        }));
````
